name: Install & test

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "media/**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm i
      - run: npm test
